[package]
name = "decent-auth-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mustache = "*"
serde = { version = "1.0", features = ["derive"] }
openidconnect = { version = "3.5.0", default-features = false }
extism-pdk = "1.3.0"
url = "2.5.3"
